### ISSUE TITLE
Documentation of the maven profiles

### ISSUE THREAD

**Issue by tatjana19** [lightblueseas/mvn-java-parent#8]
Provide a documentation of the maven profiles with examples.

**Comment by astrapi69** [comment]
@tatjana19 there are several profiles in this parent project.

The profile with the id 'update-license-header' is for generate or update the license header from source
 files. for generate or update the license header you have to run this profile with this goal license:format.

From the shell you can execute it with the following command:
```shell
:~$ mvn clean license:format -Pupdate-license-header
```
If you use eclipse:

![eclipse_update_license_header_config](https://cloud.githubusercontent.com/assets/1822320/21931968/89736fa6-d99e-11e6-9d19-0378024b4a4d.png)

The profile with the id 'release-javadoc-jar-with-dependencies' is for generate javadoc jar with dependencies.

The profile with the id 'generate-reports' is for generate javadoc jar with reports.

The profile with the id 'delombok-src-with-ant' is for generate the full java classes that are annotated with lombok annotations.

From the shell you can execute it with the following command:
```shell
:~$ mvn clean install -Pdelombok-src-with-ant
```

The profile with the id 'release-sign-artifacts' is for sign the artifacts of a project.
